version: '3'
services:
  app:
    container_name: docker-node
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    #ports:
    #  - '80:3000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:80"
